# server:
#   port: 8083

# spring:
#   application:
#     name: ms-borrowings

#   r2dbc:
#     url: r2dbc:postgresql://localhost:5432/users
#     username: postgres
#     password: pedro

#   datasource:
#     driver-class-name: org.postgresql.Driver

#   kafka:
#     bootstrap-servers: localhost:9092


#   main:
#     allow-bean-definition-overriding: true

# borrowing:
#   kafka:
#     topic: notification
    
# book:
#   service:
#     url: ${BOOK_SERVICE_URL:http://localhost:8082}

# user:
#   service:
#     url: ${USER_SERVICE_URL:http://localhost:8081}
server:
  port: 8083

spring:
  application:
    name: ms-borrowings

  r2dbc:
    # url: r2dbc:postgresql://localhost:5432/users
    url: r2dbc:postgresql://postgres-db:5432/users
    username: postgres
    password: pedro

  datasource:
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: host.docker.internal:9092

  main:
    allow-bean-definition-overriding: true

borrowing:
  kafka:
    topic: notification

book:
  service:
    url: ${BOOK_SERVICE_URL:http://com.pedro.book:8082}

user:
  service:
    url: ${USER_SERVICE_URL:http://com.pedro.users:8081}